### ISSUE TITLE
Will we implement sharding?

### ISSUE THREAD

**Issue by ferzisdis** [Boar-D-White-Foundation/kv-go#8]
I think sharding is most interesting part of distributed db. 
What do you think, will we implement it or not?
If we will, I suggest choosing an algorithm here.

**Comment by ayaz-ashrapov** [comment]
I suggest considering range-based sharding. That should reduce the number of broadcasting requests when multiple records should be retrieved

**Comment by ferzisdis** [comment]
Is there any documents to learn more about range-base sharing implementation?

**Comment by ferzisdis** [comment]
Discussed with @ayaz-ashrapov. We have concluded sharding on backend is not good for kv with raft. There is better choice to give responsibility for sharding on client.
